version: '3'
services:
  backend:
    image: nova-backend:latest
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    image: nova-frontend:latest
    build: .
    ports:
      - "3001:3000"
